"""Investigation orchestration — LLM-first (no rule verdicts).

Pipeline: incident text -> extract identifiers (regex plumbing) ->
resolve IDs via DB -> targeted log search -> correlate -> journey ->
DB evidence bundle -> ALL conclusions (verdict, suspect, fix type, RCA
narrative, fix proposals) generated by the LLM from that live evidence.

Nothing here hardcodes answers: no suspect rules, no fix-type tables, no
canned hypotheses. Without an LLM key the API returns the collected evidence
with a clear message instead of guessing.
"""

from . import dbcheck, extractor, llmreason, logsearch

# Table -> owning service, for labeling where failed rows live.
# This is schema knowledge (data plumbing), not a verdict.
TABLE_OWNER = {
    "orders": "order-service",
    "order_history": "order-service",
    "payments": "order-service",
    "provisioning": "provisioning-service",
    "reservations": "inventory-service",
    "notifications": "notification-service",
}


def _owner_from_evidence(db: dict) -> dict:
    """Name services that hold FAILED/error rows. Labels, not conclusions."""
    owners = []
    for table, rows in db.items():
        if not isinstance(rows, list):
            continue
        for r in rows:
            if not isinstance(r, dict):
                continue
            if (str(r.get("status", "")).upper() in ("FAILED", "CANCELLED", "EXPIRED")
                    or str(r.get("last_error", ""))):
                owners.append(TABLE_OWNER.get(table, table))
                break
    return {"services": owners}


def investigate(incident_text: str, mode: str = "llm") -> dict:
    entities = extractor.extract(incident_text)
    if not dbcheck.has_identifiers(entities):
        # Vague ticket: don't guess — show what's missing + fresh leads to pick from.
        # The LLM still reads the ticket + candidates so systemic issues (no single
        # ID, e.g. N+1 slowness) get a genuine verdict instead of silence.
        candidates = dbcheck.recent_candidates()
        llm = llmreason.reason(incident_text, {
            "entities": entities,
            "candidates": candidates,
            "caution": ("The candidate rows are OTHER open items shown for triage, NOT "
                        "evidence for this ticket. Do NOT cite them as the cause. Reason ONLY "
                        "from the ticket wording; keep confidence low; recommend adding an ID."),
            "note": "No traceable ID — reason from the ticket wording and candidate patterns.",
        }) if mode == "llm" else {"enabled": False, "reason": "Rule mode has no verdicts."}
        analysis = (llm.get("analysis") or {}) if llm.get("enabled") else {}
        return {
            "incident_text": incident_text,
            "entities": entities,
            "needs_info": True,
            "message": ("No traceable ID found (need at least one of: order number/id, "
                        "customer number/id, request, reservation, notification or resource number). "
                        "Pick a lead below, or rephrase with an ID from the ticket."),
            "candidates": candidates,
            "correlations": [],
            "journey": [],
            "log_lines": [],
            "log_stats": {"direct_hits": 0, "lines": 0},
            "db_evidence": {},
            "owner": {"services": []},
            "verdict": ({
                "summary": analysis.get("summary", ""),
                "root_cause": analysis.get("root_cause", ""),
                "fix_type": analysis.get("fix_type", "UNKNOWN"),
                "confidence": analysis.get("confidence", "low"),
            } if analysis else None),
            "mode": mode,
            "llm": llm,
            "safety": "READ-ONLY.",
        }
    entities = dbcheck.resolve_order_ids(entities)  # numbers -> ids before log search
    logs = logsearch.search(entities)
    db = dbcheck.collect(entities, logs)
    # Error signal required alongside the ID: an error token, a FAILED-ish status,
    # or DB state showing failure. Dates are never required.
    has_error = bool(entities.get("error_hints")) or any(
        w in entities.get("status_words", []) for w in
        ("FAILED", "CANCELLED", "EXPIRED", "SUSPENDED", "BLOCKED"))
    if not has_error:
        for rows in db.values():
            if isinstance(rows, list) and any(
                    str(r.get("status", "")).upper() in ("FAILED", "CANCELLED", "EXPIRED")
                    or str(r.get("last_error", "")) for r in rows if isinstance(r, dict)):
                has_error = True
                break
    from . import logsearch as _ls
    raw_lines = [f"[{h['service']}] {h['line']}" for h in logs["log_lines"][:60]]
    llm = llmreason.reason(incident_text, {
        "entities": entities,
        "journey": logs["journey"],
        "raw_log_lines": raw_lines,
        "db_evidence": db,
    })
    result = {
        "incident_text": incident_text,
        "entities": entities,
        "correlations": logs["correlations"],
        "journey": logs["journey"],
        "log_lines": logs["log_lines"],
        "log_stats": {"direct_hits": logs["direct_hits"], "lines": len(logs["log_lines"])},
        "db_evidence": db,
        "has_error": has_error,
        "owner": _owner_from_evidence(db),
        "verdict": None,
        "mode": mode,
        "llm": llm,
        "safety": "READ-ONLY: searched logs + SELECTs only. No data changed, nothing deployed.",
        "log_sources": {
            "mode": "pull:" + _ls.LOG_PULL_BASE if _ls.LOG_PULL_BASE else "file",
            "root": str(_ls.LOG_ROOT),
            "files": [str(_ls.LOG_ROOT / s / "app.log") for s in _ls.SERVICES],
        },
    }
    analysis = (llm.get("analysis") or {}) if llm.get("enabled") else {}
    if analysis:
        result["verdict"] = {
            "summary": analysis.get("summary", ""),
            "root_cause": analysis.get("root_cause", ""),
            "fix_type": analysis.get("fix_type", "UNKNOWN"),
            "confidence": analysis.get("confidence", "low"),
        }
    else:
        result["message"] = ("Evidence collected, but no LLM key is configured — "
                             "add LLM_API_KEY to ai-investigator/backend/.env and restart :8090 "
                             "for the verdict, RCA narrative and fix proposals. "
                             + llm.get("reason", ""))
    if not has_error:
        result["note"] = ("Ticket names an ID but describes no error — ask the model anyway, "
                          "or add the failure symptom for a sharper call.")
    return result
